config/routes.rb
SapokuWeb::Application.routes.draw do
  devise_for :users

  resources :apps

  root :to => 'home#index'

end

app/models/app.rb
class App < ActiveRecord::Base
  # attr_accessible :title, :body

  validates_uniqueness_of :name

  belongs_to :user

  def to_param
    self.name
  end

  def is_bootstrap_done?
    self.bootstraped == 2
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :apps

  validates_uniqueness_of :ssh_public_key

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :ssh_public_key
  # attr_accessible :title, :body

  after_create :add_key_to_master_repo

  def add_key_to_master_repo
    RepoHelper.execute REPO_PATH do |helper|
      helper.add_user_key self.id, self.ssh_public_key.split(" ")[1]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@apps = App.find_all_by_user_id(current_user.id)
	end

	def new
		@app = App.new
	end

	def create
		@app = App.new
		@app.user = current_user
		@app.name = params[:app][:name].downcase.gsub(' ','_')
		if @app.save
			
			BootstrapTadpole.perform_async(@app.id, params[:type].to_i)

			if params[:type].to_i != 2
				#dont bootstrap git if we're creating an html stack
				BootstrapGit.perform_async(@app.id)
			end
			
			redirect_to @app
		end
	end

	def show
		@app = App.find_by_name params[:id]
	end

	def destroy
		@app = App.find_by_name params[:id]
		@app.destroy

		AppCleaner.perform_async @app.name

		redirect_to '/'
	end

	def rollback
		@app = App.find_by_name params[:id]
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		#redirect_to apps_path if user_signed_in?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apps/_app.html.erb
<% pole = Tadpole.find(app.name) %>
<tr>
	<td><%= link_to app.name, app %></td>
	<td><%= pole.stack %> <%= image_tag("ruby.png", :class => "tiny") %></td>
	<td><%= pole.container_ip %></td>
	<td><%= pole.local_port %></td>
	<td>
		<% if !pole.running? %>
			<span class="ink-label caution">Down<span>
		<% else %>
			<span class="ink-label success">Running<span>
		<% end %>
	</td>
	<td style="width:80px;">
		<a href="http://<%= app.name %>.sapoku.webreakstuff.com" class="ink-button">Open</a>
	</td>
</tr>

app/views/apps/index.html.erb
<div class="ink-l100 mb center">
	<h2><i class="icon-dashboard icon-large"></i> Your current apps</h2>
</div>

<% if @apps.empty? %>
	<p class="ink-vspace">No apps yet. <%= link_to 'Click here', new_app_path %> to create one.</p>
<% else %>
	<table class="ink-table ink-bordered ink-zebra ink-hover ink-vspace">
		<thead>
			<th>App name</th>
			<th>Stack</th>
			<th>Internal IP</th>
			<th>Port</th>
			<th>Status</th>
			<th style="width:80px;">Ops</th>
		</thead>
		<tbody>
			<%= render @apps %>
		</tbody>
	</table>
<% end %>

<%= link_to('Add a new app', new_app_path, :class => "ink-button") %>

app/views/apps/new.html.erb
<div class="ink-l100 mb center">
	<h2><i class="icon-bolt icon-large"></i> The incredible app-o-maker&trade;</h2>
</div>

<%= form_for @app, :html => {:class => 'ink-form block ink-l50'} do |f| %>
	<fieldset>
		<h3>Create your app</h3>
		<div class="control">
			<%= f.label :name %>
			<%= f.text_field :name %>
			<p class="tip space short">this will be used for the url. no spaces please.</p>
		</div>
		<div class="control">
			<label for="type">Pick your stack</label>
			<select id="type" name="type">
				<option value="0">Ruby</option>
				<option value="0">Node (soon)</option>
				<option value="0">Plain HTML (soon)</option>
			</select>
		</div>
	</fieldset>
	<button class="ink-button success">Launch my app</button>
<% end %>

<div class="ink-l50">
	<div class="ink-gutter">
		<h3>Getting started</h3>
		<p>Getting started with Sapoku is easy. Create your first app by selecting one of our available stacks. The name of the app becomes the URL on which it is accessible, such as <mark>myapp.sapoku.webreakstuff.com</mark>. Once we are done creating your container, you'll be taken to the container details page automatically.</p>
	</div>
</div>

app/views/apps/show.html.erb
<% if @app.is_bootstrap_done? %>
<% pole = Tadpole.find(@app.name) %>

<div class="ink-l100 mb center">
	<h2><i class="icon-cloud icon-large"></i> <%= @app.name %> is currently <% if !pole.running? %><span class="ink-label caution">Down<span><% else %><span class="ink-label success">Running<span><% end %></h2>
</div>

<table class="ink-table ink-bordered ink-zebra ink-hover ink-vspace">
	<thead>
		<th>Stack</th>
		<th>Internal IP</th>
		<th>Port</th>
		<th>Status</th>
		<th style="width:80px;">Ops</th>
	</thead>
	<tbody>
		<tr>
			<td><%= pole.stack %> <%= image_tag("ruby.png", :class => "tiny") %></td>
			<td><%= pole.container_ip %></td>
			<td><%= pole.local_port %></td>
			<td>
				<% if !pole.running? %>
					<span class="ink-label caution">Down<span>
				<% else %>
					<span class="ink-label success">Running<span>
				<% end %>
			</td>
			<td style="width:80px;">
				<a href="http://<%= @app.name %>.sapoku.webreakstuff.com" class="ink-button">Open</a>
			</td>
		</tr>
	</tbody>
</table>

<div class="ink-l100 ink-vspace">
	<h3>Deploying your application</h3>
	<ol>
		<li>Work on your application</li>
		<li>
			Add our remote to your git repository<br/>
			<code><mark>git remote add sapoku git@sapoku.webreakstuff.com:<%= @app.name %>.git</mark></code>
		</li>
		<li>
			When ready to deploy, push to sapoku<br/>
			<code><mark>git push sapoku master</mark></code>
		</li>
		<li>You're done! <a href="http://<%= @app.name %>.sapoku.webreakstuff.com">Refresh your browser</a>.</li>
	</ol>
</div>

<hr/>
<p><%= link_to "Delete app", @app, :method => :delete, :confirm => 'Are you really sure? There is no turning back!', :class => "ink-button caution" %> </p>

<% else %>
	<%= content_for :header do %>
		<meta http-equiv="refresh" content="3"/>
	<% end %>
	<div class="ink-alert ink-vspace"><p>Our ninjas are working hard to summon your app to life. Please wait a few moments longer!</p></div>
<% end %>

app/views/home/index.html.erb
<div class="center ink-l100 ink-vspace" id="header">
	<%= image_tag("ninja.png") %>
	<h2>Sapoku: instant app-deployments to the cloud</h2>
</div>

<div class="center">
	<p class="mb">We love you long time, yes?<br>We spend so much time loving you,<br>we make no homepage.</p>

	<%= link_to('New account', new_user_registration_path, :class => "ink-button success") %>
	<%= link_to('Login to account', new_user_session_path, :class => "ink-button info") %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="no-js">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Sapoku &mdash; Codebits</title>
        <meta name="description" content="">
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">

		<!-- Stylesheets -->
		<link rel="stylesheet" href="http://css.ink.sapo.pt/v1/css/ink.css">
		<!-- Js -->
		<script type="text/javascript" src="http://js.sapo.pt/Bundles/Ink-v1.js"></script>
		<!--[if IE]>
			<link rel="stylesheet" href="http://css.ink.sapo.pt/v1/css/ink-ie.css" type="text/css" media="screen" title="no title" charset="utf-8">
		<![endif]-->
		<%= stylesheet_link_tag "application", :media => "all" %>

		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= yield :header %>
	</head>
	<body>
		<div id="mainwrap" class="ink-container">
			<nav class="ink-navigation ink-l100 mb">
				<ul class="menu horizontal black">
					<li class="ink-title"><%= link_to 'Sapoku', apps_path %></li>
					<% if user_signed_in? %>
						<li class="right"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
						<li class="right"><%= link_to('Create App', new_app_path ) %></li>
					<% else %>
						<li class="right"><%= link_to('Login', new_user_session_path)  %></li>
					<% end %>
				</ul>
			</nav>

			<% if flash.notice %><div class="ink-alert success"><button class="ink-close">&times;</button><p><%= flash.notice %></p></div><% end %>
			<% if flash.alert %><div class="ink-alert error"><button class="ink-close">&times;</button><p><%= flash.alert %></p></div><% end %>

			<div class="ink-l100 ink-s100">
      			<%= yield %>
   			</div>
		</div>
    <footer>
      <div class="ink-container">
        <p class="copyright">
          &copy; 2012 Sapoku &mdash; Codebits VI - Built with <i class="icon-heart icon-small"></i> by <a href="http://webreakstuff.com">Webreakstuff</a> &amp; <a href="http://biasedbit.com">Biasedbit</a>
        </p>
      </div>
    </footer>
	</body>
</html>